name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: [3.6, 3.7, 3.8, 3.9]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install code and dev dependencies
        run: |
          pip install -e .[dev]
          pip freeze

      - name: Lint
        run: |
          flake8 --show-source --ignore=E226,E301,E302,E305,E306,E501,W503,W504
          mypy -p omnidice

      - name: Test without Pandas
        run: pytest --cov=omnidice --cov-branch --cov-report=term

      - name: Install Pandas
        run: |
          pip install pandas
          pip freeze

      - name: Test with Pandas
        env:
          OMNIDICE_TST_ORE_SIZE_LIMIT: 10
        run: pytest --cov=omnidice --cov-branch --cov-append --cov-report=xml --cov-report=term

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          env_vars: OS,PYTHON
