name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install code and dev dependencies
        run: |
          pip install -e .[dev]
          pip freeze

      - name: Lint
        run: |
          flake8 --show-source --ignore=E226,E301,E302,E305,E306,E501,W503,W504
          mypy -p omnidice

      - name: Test without Pandas
        run: pytest

      - name: Test with Pandas
        run: |
          pip install pandas
          pip freeze
          pytest

      - name: Build wheel
        run: python setup.py bdist_wheel
